var request = require('request');

var emojis = {
    "innocent face": "ʘ‿ʘ",
    "reddit disapproval face": "ಠ_ಠ",
    "table flip": "(╯°□°）╯︵ ┻━┻",
    "put the table back": "┬─┬﻿ ノ( ゜-゜ノ)",
    "tidy up": "┬─┬⃰͡ (ᵔᵕᵔ͜ )",
    "double flip": "┻━┻ ︵ヽ(`д´)ﾉ︵﻿ ┻━┻",
    "fisticuffs": "ლ(｀ー´ლ)",
    "cute bear": "ʕ•ᴥ•ʔ",
    "squinting bear": "ʕᵔᴥᵔʔ",
    "gtfo bear": "ʕ •`ᴥ•´ʔ",
    "cute face with big eyes": "(｡◕‿◕｡)",
    "surprised": "（　ﾟдﾟ）",
    "shrug face": "¯\_(ツ)_/¯",
    "meh": "¯\(°_o)/¯",
    "feel perky": "(`･ω･´)",
    "angry face": "(╬ ಠ益ಠ)",
    "at what cost": "ლ(ಠ益ಠლ)",
    "excited": "☜(⌒▽⌒)☞",
    "running": "ε=ε=ε=┌(;*´д`)ﾉ",
    "happy face": "ヽ(´▽`)/",
    "basking in glory": "ヽ(´ー｀)ノ",
    "kitty emote": "ᵒᴥᵒ#",
    "fido": "v•ᴥ•v",
    "meow": "ฅ^•ﻌ•^ฅ",
    "cheers": "（ ^_^）o自自o（^_^ ）",
    "devious smile": "ಠ‿ಠ",
    "chan emoticon": "( ͡° ͜ʖ ͡°)",
    "crying face": "ಥ_ಥ",
    "breakdown": "ಥ﹏ಥ",
    "disagree": "٩◔̯◔۶",
    "flexing": "ᕙ(⇀‸↼‶)ᕗ",
    "do you even lift bro": " ᕦ(ò_óˇ)ᕤ",
    "kirby": "⊂(◉‿◉)つ",
    "tripping out": "q(❂‿❂)p",
    "discombobulated": "⊙﹏⊙",
    "sad and confused": "¯\_(⊙︿⊙)_/¯",
    "japanese lion face": "°‿‿°",
    "confused": "¿ⓧ_ⓧﮌ",
    "confused scratch": "(⊙.☉)7",
    "worried": "(´･_･`)",
    "dear god why": "щ（ﾟдﾟщ）",
    "staring": "٩(๏_๏)۶",
    "pretty eyes": "ఠ_ఠ",
    "strut": "ᕕ( ᐛ )ᕗ",
    "zoned": "(⊙_◎)",
    "crazy": "ミ●﹏☉ミ",
    "trolling": "༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽",
    "angry troll": "ヽ༼ ಠ益ಠ ༽ﾉ",
    "fuck it": "t(-_-t)",
    "sad face": "(ಥ⌣ಥ)",
    "hugger": "(づ￣ ³￣)づ",
    "stranger danger": "(づ｡◕‿‿◕｡)づ",
    "cry face": "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡",
    "cry troll": "༼ ༎ຶ ෴ ༎ຶ༽",
    "tgif": "ヽ(´▽｀)ノ",
    "dancing": "┌(ㆆ㉨ㆆ)ʃ",
    "sleepy": "눈_눈",
    "angry birds": "( ఠൠఠ )ﾉ",
    "no support": "乁( ◔ ౪◔)「      ┑(￣д ￣)┍",
    "shy": "(๑•́ ₃ •̀๑)",
    "fly away": "⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾",
    "careless": "◔_◔",
    "love": "♥‿♥",
    "touchy feely": "ԅ(≖‿≖ԅ)",
    "kissing": "( ˘ ³˘)♥",
    "shark face": "( ˇ෴ˇ )",
    "emo dance": "ヾ(-_- )ゞ",
    "dance": "♪♪ ヽ(ˇ∀ˇ )ゞ",
    "opera": "ヾ(´〇`)ﾉ♪♪♪",
    "winnie the pooh": "ʕ •́؈•̀)",
    "boxing": "ლ(•́•́ლ)",
    "fight": "(ง'̀-'́)ง",
    "listening to headphones": "◖ᵔᴥᵔ◗ ♪ ♫",
    "robot": "{•̃_•̃}",
    "seal": "(ᵔᴥᵔ)",
    "questionable": "(ծ‸ ծ)",
    "winning": "(•̀ᴗ•́)و ̑̑",
    "zombie": "[¬º-°]¬",
    "pointing": "(☞ﾟヮﾟ)☞",
    "whistling": "(っ•́｡•́)♪♬",
    "injured": "(҂◡_◡)",
    "creeper": "ƪ(ړײ)‎ƪ​​",
    "eye roll": "⥀.⥀",
    "flying": "ح˚௰˚づ",
    "things that cant be unseen": "♨_♨",
    "looking down": "(._.)",
    "im a_hugger": "(⊃｡•́‿•̀｡)⊃",
    "wizard": "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ",
    "yum": "(っ˘ڡ˘ς)",
    "judging": "( ఠ ͟ʖ ఠ)",
    "tired": "( ͡ಠ ʖ̯ ͡ಠ)",
    "dislike": "( ಠ ʖ̯ ಠ)",
    "hitchhiking": "(งツ)ว",
    "satisfied": "(◠﹏◠)",
    "sad and crying": "(ᵟຶ︵ ᵟຶ)",
    "stunna shades": "(っ▀¯▀)つ",
    "chicken": "ʚ(•｀",
    "barf": "(´ж｀ς)",
    "fuck off": "(° ͜ʖ͡°)╭∩╮",
    "smiley toast": "ʕʘ̅͜ʘ̅ʔ",
    "exorcism": "ح(•̀ж•́)ง †",
    "love": "-`ღ´-",
    "taking a_dump": "(⩾﹏⩽)",
    "dab": "ヽ( •_)ᕗ",
    "wave dance": "~(^-^)~",
    "happy hug": "\(ᵔᵕᵔ)/",
    "resting my eyes": "ᴖ̮ ̮ᴖ",
    "peepers": "ಠಠ",
    "judgemental": "{ಠʖಠ}",
    "flip friend": "(ノಠ ∩ಠ)ノ彡( \o°o)\ ",
    "shrug": "¯\\_(ツ)_/¯",
    "flex": "ᕙ(⇀‸↼‶)ᕗ",
    "flip table": "(╯°□°）╯︵ ┻━┻",
    "flip all tables": "┻━┻︵ \\(°□°)/ ︵ ┻━┻",
    "angry face": "(⋟﹏⋞)",
    "this guy": "(☞ﾟ∀ﾟ)☞",
    "zombie": "[¬º-°]¬",
    "face palm": "-.(\\",
    "crying": ".·´¯`(>▂<)´¯`·.",
    "love": "(♥_♥)",
    "hugs": "(っ◕‿◕)っ",
    "coffee": "c[_]",
    "fight me": "(ง •̀_•́)ง",
    "sparkle": "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
    "why?!": "ლ( `д’ ლ)",
    "dance": "ᕕ(⌐■_■)ᕗ ♪♬",
    "punch": "o=(-q)",
    "meditation": "‿( ́ ̵ _-`)‿",
    "pig": "^(*(oo)*)^",
    "mouse": "----{,_,\">",
    "zoidberg": "(\\/) (;,,;) (\\/)",
    "spider": "/x\\(-)/x\\",
    "monkey": "@(_)@",
    "deal with it": "( •_•)>⌐■-■ (⌐■_■)",
    "koala": "@( * o * )@",
    "dog": "ˁ˚ᴥ˚ˀ",
    "put table back": "┏━┓ ︵ /(^.^/)",
    "metal": "\\m/_(>_<)_\\m/",
    "glasses": "ᒡ◯ᵔ◯ᒢ",
    "kitty": "=^..^=",
    "sword": "@xxxx[{::::::::::::::>",
    "ping pong": "( _)0*´¯`·.¸.·´¯`°q(_ )",
    "airplane": "✈",
    "cassette": "[●▪▪●]",
    "pac man": "ᗧ···ᗣ···ᗣ··",
    "caterpillar": "(,(,(,(,(,(,(,(, \")",
    "dumbbell": "❚█══█❚",
    "emo": "(///_ ;)",
    "bird": "~(‾▿‾)~",
    "panda": "ヽ(￣(ｴ)￣)ﾉ",
    "domino": "[: :|:::]",
    "singing": "♪└(￣◇￣)┐♪",
    "shark attack": "~~~~~~\\o/~~~~~/\\~~~~~",
    "guitar": "c====(=#o| )",
    "cat": "=^..^="
    "sniper": "︻デ┳═ー",
    "shocked": "(∩╹□╹∩)",
    "monocle": "(╭ರ_•́)",
    "piggy": "(∩◕(oo)◕∩)",
    "fish": ">°))))彡",
    "camera": "[◉\"]",
    "arrow": "»»---------------►",
    "canoe": "~~~~╘══╛~~~~",
    "what????": "(ͼ˳ͽ)..!!!",
    "oh hi!": "┬┴┬┴┤･ω･)ﾉ├┬┴┬┴",
    "kisses": "(づ ￣ ³￣)づ",
    "neo": "(⌐■_■)--︻╦╤─ - - -",
    "rose": "-----------<----(@",
    "lenny": "( ͡° ͜ʖ ͡°)",
    "snail": "@_''''-''''",
    "jake": "ˁ(oᴥo)ˀ",
    "dice": "[::] [::]",
    "snowing": "✲´*。.❄¨¯`*✲。❄。*。",
    "cthulhu": "^(;,;)^",
    "tie fighter": "|-o-|",
    "trumpet": "-=iii=<()",
    "wizard": "(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ. *",
    "wat": "ಠ_ಠ",
    "haters gonna hate": "ᕕ( ᐛ )ᕗ",
    "rage": "ლ(ಠ益ಠ)ლ",
    "upside down lenny": "( ͜。 ͡ʖ ͜。)",
    "race car": "ō͡≡o˞̶",
    "bear": "ˁ(⦿ᴥ⦿)ˀ",
    "chu": "(´ε｀ )",
    "boobs": "( . y . )",
    "polar bear": "ʕ·͡ᴥ·ʔ",
    "peace": "(‾⌣‾)♉",
    "rage face": "ლ(ಠ益ಠ)ლ",
    "barbell": "❚█══█❚",
    "capital building": "๑۩۩๑",
    "rock on": "\\m/ (>.<) \\m/",
    "flip off": "(ಠ_ಠ)┌∩┐",
    "nope": "t(-_-t)",
    "crowd": "(-(-_(-_-)_-)-)",
    "butt": "(‿|‿)",
    "fox": "-^^,--,~",
    "hit": "█▬█ █ ▀█▀",
    "needle": "┣▇▇▇═─",
    "upc": "║▌║█║▌│║▌║▌█",
    "shoot": "(◕_◕)=ε/̵͇̿̿/''''̿''''̿ ̿",
    "sophie": "<xx\"\"xx>",
    "joy": "n_n",
    "bautista": "(╯°_°）╯︵ ━━━",
    "robot": "d[o_0]b",
    "smooth": "(づ ￣ ³￣)づ ⓢⓜⓞⓞⓣⓗ",
    "fuckall": "╭∩╮（︶︿︶）╭∩╮",
    "skrillex": "ϟƙʀɩןןσx﻿",
    "flower power": "ヽ(·̿̿ĺ̯̿̿·̿✿)ﾉ",
    "table flip": "(╯°□°）╯︵ ┻━┻",
    "pancakes?": "( ^-^)_旦",
    "unicorn": "?",
    "binding of isaac": "(¡ ¡)",
    "joint": "<\\\\\\\\> ~~~~",
    "cigar": "(\\\\\\| ~~~",
    "sword 2": "▬▬ι═══════>",
    "die": "[::]",
    "middle fingers": "┌∩┐(◣ _ ◢)┌∩┐",
    "headphones": "d[-_-]b",
    "butterfly": "ƹ̵̡ӝ̵̨̄ʒ",
    "cries": "(╯︵╰,)",
    "im going for a walk": "ᕕ( ᐛ )ᕗ",
    "spooky": "‹’’›(ͼ˳ͽ)‹’’›",
    "happily flip tables": "┻━┻ ︵ ლ(⌒-⌒ლ)",
    "bear flip table": "ʕノ•ᴥ•ʔノ ︵ ┻━┻",
    "owo": "owo",
    "kilroy": "ɯ-(ꞌʊꞌ)-ɯ",
    "sailor moon": "/¯\\_/°^_^°\\_/¯\\",
    "kita": "ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!",
    "cheers": "( ^​_^）o自自o（^_​^ )",
    "bear with outstretched arms": "ʕつ•ᴥ•ʔつ",
    "disapproving bear with outstretched arms flipping": "ʕつಠᴥಠʔつ ︵ ┻━┻",
    "creep bear with outstretched arms": "ʕつ ͡°ᴥ ͡°ʔつ",
    "pup": "ᶘ ◕ᴥ◕ᶅ",
    "bear with glasses": "ʕ⌐■ᴥ■ʔ",
    "bear putting on glasses": "ʕつ•ᴥ•ʔつ⌐■-■",
    "bear replacing table": "┬─┬ ノʕ•ᴥ•ノʔ",
    "bear with doubting eyes": "ʕಠಿᴥಠʔ",
    "council of disapproval": "ʕಠᴥಠʔ ಠ_ಠ ᶘಠᴥಠᶅ",
    "council of doubt": "ʕಠಿᴥಠʔ ಠಿ_ಠ ᶘಠಿᴥಠᶅ",
    "hugme": "／人 ⌒ ‿‿ ⌒ 人＼",
    "stick up your dukes": "(ง’-‘)ง",
    "rare": "┌ಠ_ಠ)┌∩┐ ᶠᶸᶜᵏ♥ᵧₒᵤ",
    "love you": "ᵛᵉᵧₒᵤᶫᵒᵛᵉᵧₒᵤ ᶫᵒᵛᵉᵧₒᵤ",
    "crayons": "((̲̅ ̲̅(̲̅c̲̅r̲̅a̲̅y",
    "hu hu": "█▬█ █▄█ █▬█ █▄█",
    "manatee": "(◕('''' 人 '''') ◕)",
    "salesforce": "(╯°□°）╯︵ ǝɔɹoɟsǝlɐs",
    "council of approval": "(/◕ヮ◕)/ (^o^) (✿◠‿◠)",
    "mega rage": "＼＼\\٩(๑`^´๑)۶//／／",
    "ffuuu": "ೕ(ò⺫ ó )೨",
    "bow": "o(_ _)o",
    "sorry": "ヾ(_ _。）",
    "dongers": "ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ",
    "wat-wat": "σ(‘◉⌓◉’)",
    "blank": ": ◉ ∧ ◉ : ╏",
    "dunno": "٩(๏̯๏)۶",
    "indeed": "ಠ_ರೃ",
    "wtf why": "(｢๑•₃•)｢ ʷʱʸ?",
    "dead eyes": "¿ⓧ_ⓧﮌ",
    "i'm out": "x‿x",
    "satan": "↑_(φwφ;)ψ",
    "hail satan": "↑_(φwφ;)ψ",
    "bomb": "!!(　’ ‘)ﾉﾉ⌒●~*",
    "sleepy coffee": "( -_-)旦~",
    "high five": "( ⌒o⌒)人(⌒-⌒ )v",
    "wtf dude?": "＼(◑д◐)＞∠(◑д◐)",
    "fail": "o(╥﹏╥)o",
    "angry hug": "(つ◉益◉)つ",
    "it's cool bro": "༼ つ ▀_▀ ༽つ",
    "fungry": "σ_(꒪ཀ꒪」∠)_",
    "derp": "ヘ（。□°）ヘ",
    "drowning": "人人人ヾ( ;×o×)〃 人人人",
    "almost cared": "╰╏ ◉ 〜 ◉ ╏╯",
    "blow me": "ₒ₍₊˒₃˓₎ₒ▁▂▃▅▆▓▒░✩",
    "yessir": "∠(･`_´･ )",
    "oh you": "(n˘v˘•)¬",
    "coffee now": "{zzz}°°°( -_-)>c[_]",
    "fix table": "(ヘ･_･)ヘ┳━┳",
    "omg yes": "(๑˃̵ᴗ˂̵)و",
    "epic win": "＼ ٩( ᐛ )و /／",
    "squee": "ヾ(◎o◎,,；)ﾉ",
    "round cat": "~(^._.)",
    "round bird": ",(u°)>",
    "y u no": "ლ(ಠ_ಠლ)",
    "hoxom": "h(o x o )m",
    "squid": "くコ:彡",
    "angry shrug": "¯\\_| ಠ ∧ ಠ |_/¯",
    "man spider": "/╲/\\༼ *ಠ 益 ಠ* ༽/\\╱\\",
    "crowd 2": "༼ ºل͟º༼ ºل͟º ༽ºل͟º ༽",
    "spell cast": "╰( ⁰ ਊ ⁰ )━☆ﾟ.*･｡ﾟ",
    "jazz musician": "ヽ(⌐■_■)ノ♪♬",
    "myancat": "mmmyyyyy<⦿⽘⦿>aaaannn",
    "gimme": "༼ つ ◕_◕ ༽つ",
    "kyle": "♥♥ˁ(⦿ᴥ⦿)ˀ♥♥",
    "could not find items that match search term.": "ʕノ•ᴥ•ʔノ ︵ ┻━┻",
    "crab": "(\\|) ._. (|/)",
    "gun": "▄︻┻═━一",
    "playing in snow": "(╯^□^)╯︵ ❄☃❄",
    "sniper rifle": "︻デ┳═ー",
    "sunglasses": "(•_•)>⌐■-■ (⌐■_■)",
    "frog eating a fly": "8)~~~~~ *",
    "lodash flip": "(╯°□°）╯︵ ɥsɐpoן",
    "fingers": "┌∩┐(◣_◢)┌∩┐",
    "mac": "",
    "trick": "+1 @skardude",
    "victory!": "v(-.o)v",
    "don fuller": "╭∩╮(ο_ο)╭∩╮",
    "sad donger": "ヽ༼ຈʖ̯ຈ༽ﾉ",
    "sad lenny": "( ͡° ʖ̯ ͡°)",
    "riot": "୧༼ಠ益ಠ༽୨",
    "porcupine": "(•ᴥ• )́`́''''́`́''''́⻍",
    "point": "(☞ﾟヮﾟ)☞",
    "hadouken": "༼つಠ益ಠ༽つ ─=≡σo))",
    "kawaï": "∩( ・ω・)∩",
    "afraid": "(　ﾟ дﾟ)",
    "laughing": "(＾▽＾)",
    "drunkenness": "ヽ（´ー｀）┌",
    "energy": "つ ◕_◕ ༽つ つ ◕_◕ ༽つ",
    "exchange": "(╯°□°）╯︵ ǝƃuɐɥɔxǝ",
    "error": "(╯°□°)╯︵ ɹoɹɹǝ",
    "bat": "/\\^⠤^/\\",
    "german flag": "??",
    "bullseye": "?",
    "pirate flag": "?‍☠️",
    "disapprove": "ಠ_ಠ",
    "baby yoda": "<´(• ﻌ •)`>",
    "crying / depressed hug": "(っ °д °;)っ",
    "uwu / cute face": "(uwu)",
    "what (waat)": "＼（〇_ｏ）／",
    "scream ghost": ".----------."
}

exports.inspire = (req, res, next) => {
  var botPayload = {
    attachments: [],
    response_type: 'in_channel',
  };
  
  try {
    botPayload.text = emojis[req.body.text];
  } catch (e) {
    botPayload.text = "";
  }

  return res.status(200).json(botPayload);
}
