var request = require('request');

var emojis = {
    "afraid": "( ﾟ дﾟ)",
    "airplane": "✈",
    "almost cared": "╰╏ ◉ 〜 ◉ ╏╯",
    "angry birds": "( ఠൠఠ )ﾉ",
    "angry face": "(⋟﹏⋞)",
    "angry hug": "(つ◉益◉)つ",
    "angry shrug": "¯\\_| ಠ ∧ ಠ |_/¯",
    "angry troll": "ヽ༼ ಠ益ಠ ༽ﾉ",
    "arrow": "»»---------------►",
    "at what cost": "ლ(ಠ益ಠლ)",
    "baby yoda": "<´(• ﻌ •)`>",
    "barbell": "❚█══█❚",
    "barf": "(´ж｀ς)",
    "basking in glory": "ヽ(´ー｀)ノ",
    "bat": "/\\^⠤^/\\",
    "bautista": "(╯°_°）╯︵ ━━━",
    "bear flip table": "ʕノ•ᴥ•ʔノ ︵ ┻━┻",
    "bear putting on glasses": "ʕつ•ᴥ•ʔつ⌐■-■",
    "bear replacing table": "┬─┬ ノʕ•ᴥ•ノʔ",
    "bear with doubting eyes": "ʕಠಿᴥಠʔ",
    "bear with glasses": "ʕ⌐■ᴥ■ʔ",
    "bear with outstretched arms": "ʕつ•ᴥ•ʔつ",
    "bear": "ˁ(⦿ᴥ⦿)ˀ",
    "binding of isaac": "(¡ ¡)",
    "bird": "~(‾▿‾)~",
    "blank": ": ◉ ∧ ◉ : ╏",
    "blow me": "ₒ₍₊˒₃˓₎ₒ▁▂▃▅▆▓▒░✩",
    "bomb": "!!( ’ ‘)ﾉﾉ⌒●~*",
    "boobs": "( . y . )",
    "bow": "o(_ _)o",
    "boxing": "ლ(•́•́ლ)",
    "breakdown": "ಥ﹏ಥ",
    "bullseye": "?",
    "butt": "(‿|‿)",
    "butterfly": "ƹ̵̡ӝ̵̨̄ʒ",
    "camera": "[◉\"]",
    "canoe": "~~~~╘══╛~~~~",
    "capital building": "๑۩۩๑",
    "careless": "◔_◔",
    "cassette": "[●▪▪●]",
    "cat": "=^..^=",
    "caterpillar": "(,(,(,(,(,(,(,(, \")",
    "chan emoticon": "( ͡° ͜ʖ ͡°)",
    "cheers": "（ ^_^）o自自o（^_^ ）",
    "chicken": "ʚ(•｀",
    "chu": "(´ε｀ )",
    "cigar": "(\\\\\\| ~~~",
    "coffee now": "{zzz}°°°( -_-)>c[_]",
    "coffee": "c[_]",
    "confused scratch": "(⊙.☉)7",
    "confused": "¿ⓧ_ⓧﮌ",
    "could not find items that match search term.": "ʕノ•ᴥ•ʔノ ︵ ┻━┻",
    "council of approval": "(/◕ヮ◕)/ (^o^) (✿◠‿◠)",
    "council of disapproval": "ʕಠᴥಠʔ ಠ_ಠ ᶘಠᴥಠᶅ",
    "council of doubt": "ʕಠಿᴥಠʔ ಠಿ_ಠ ᶘಠಿᴥಠᶅ",
    "crab": "(\\|) ._. (|/)",
    "crayons": "((̲̅ ̲̅(̲̅c̲̅r̲̅a̲̅y",
    "crazy": "ミ●﹏☉ミ",
    "creep bear with outstretched arms": "ʕつ ͡°ᴥ ͡°ʔつ",
    "creeper": "ƪ(ړײ)‎ƪ​​",
    "cries": "(╯︵╰,)",
    "crowd 2": "༼ ºل͟º༼ ºل͟º ༽ºل͟º ༽",
    "crowd": "(-(-_(-_-)_-)-)",
    "cry face": "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡",
    "cry troll": "༼ ༎ຶ ෴ ༎ຶ༽",
    "crying / depressed hug": "(っ °д °;)っ",
    "crying face": "ಥ_ಥ",
    "crying": ".·´¯`(>▂<)´¯`·.",
    "cthulhu": "^(;,;)^",
    "cute bear": "ʕ•ᴥ•ʔ",
    "cute face with big eyes": "(｡◕‿◕｡)",
    "dab": "ヽ( •_)ᕗ",
    "dance": "♪♪ ヽ(ˇ∀ˇ )ゞ",
    "dancing": "┌(ㆆ㉨ㆆ)ʃ",
    "dead eyes": "¿ⓧ_ⓧﮌ",
    "deal with it": "( •_•)>⌐■-■ (⌐■_■)",
    "dear god why": "щ（ﾟдﾟщ）",
    "derp": "ヘ（。□°）ヘ",
    "devious smile": "ಠ‿ಠ",
    "dice": "[::] [::]",
    "die": "[::]",
    "disagree": "٩◔̯◔۶",
    "disapprove": "ಠ_ಠ",
    "disapproving bear with outstretched arms flipping": "ʕつಠᴥಠʔつ ︵ ┻━┻",
    "discombobulated": "⊙﹏⊙",
    "dislike": "( ಠ ʖ̯ ಠ)",
    "do you even lift bro": " ᕦ(ò_óˇ)ᕤ",
    "dog": "ˁ˚ᴥ˚ˀ",
    "domino": "[: :|:::]",
    "don fuller": "╭∩╮(ο_ο)╭∩╮",
    "dongers": "ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ",
    "double flip": "┻━┻ ︵ヽ(`д´)ﾉ︵ ┻━┻",
    "drowning": "人人人ヾ( ;×o×)〃 人人人",
    "drunkenness": "ヽ（´ー｀）┌",
    "dumbbell": "❚█══█❚",
    "dunno": "٩(๏̯๏)۶",
    "emo dance": "ヾ(-_- )ゞ",
    "emo": "(///_ ;)",
    "energy": "つ ◕_◕ ༽つ つ ◕_◕ ༽つ",
    "epic win": "＼ ٩( ᐛ )و /／",
    "error": "(╯°□°)╯︵ ɹoɹɹǝ",
    "exchange": "(╯°□°）╯︵ ǝƃuɐɥɔxǝ",
    "excited": "☜(⌒▽⌒)☞",
    "exorcism": "ح(•̀ж•́)ง †",
    "eye roll": "⥀.⥀",
    "face palm": "-.(\\",
    "fail": "o(╥﹏╥)o",
    "feel perky": "(`･ω･´)",
    "ffuuu": "ೕ(ò⺫ ó )೨",
    "fido": "v•ᴥ•v",
    "fight me": "(ง •̀_•́)ง",
    "fight": "(ง'̀-'́)ง",
    "fingers": "┌∩┐(◣_◢)┌∩┐",
    "fish": ">°))))彡",
    "fisticuffs": "ლ(｀ー´ლ)",
    "fix table": "(ヘ･_･)ヘ┳━┳",
    "flex": "ᕙ(⇀‸↼‶)ᕗ",
    "flexing": "ᕙ(⇀‸↼‶)ᕗ",
    "flip all tables": "┻━┻︵ \\(°□°)/ ︵ ┻━┻",
    "flip friend": "(ノಠ ∩ಠ)ノ彡( \\o°o)\\ ",
    "flip off": "(ಠ_ಠ)┌∩┐",
    "flip table": "(╯°□°）╯︵ ┻━┻",
    "flower power": "ヽ(·̿̿ĺ̯̿̿·̿✿)ﾉ",
    "fly away": "⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾",
    "flying": "ح˚௰˚づ",
    "fox": "-^^,--,~",
    "frog eating a fly": "8)~~~~~ *",
    "fuck it": "t(-_-t)",
    "fuck off": "(° ͜ʖ͡°)╭∩╮",
    "fuckall": "╭∩╮（︶︿︶）╭∩╮",
    "fungry": "σ_(꒪ཀ꒪」∠)_",
    "german flag": "??",
    "gimme": "༼ つ ◕_◕ ༽つ",
    "glasses": "ᒡ◯ᵔ◯ᒢ",
    "gtfo bear": "ʕ •`ᴥ•´ʔ",
    "guitar": "c====(=#o| )",
    "gun": "▄︻┻═━一",
    "hadouken": "༼つಠ益ಠ༽つ ─=≡σo))",
    "hail satan": "↑_(φwφ;)ψ",
    "happily flip tables": "┻━┻ ︵ ლ(⌒-⌒ლ)",
    "happy face": "ヽ(´▽`)/",
    "happy hug": "\\(ᵔᵕᵔ)/",
    "haters gonna hate": "ᕕ( ᐛ )ᕗ",
    "headphones": "d[-_-]b",
    "high five": "( ⌒o⌒)人(⌒-⌒ )v",
    "hit": "█▬█ █ ▀█▀",
    "hitchhiking": "(งツ)ว",
    "hoxom": "h(o x o )m",
    "hu hu": "█▬█ █▄█ █▬█ █▄█",
    "hugger": "(づ￣ ³￣)づ",
    "hugme": "／人 ⌒ ‿‿ ⌒ 人＼",
    "hugs": "(っ◕‿◕)っ",
    "i'm out": "x‿x",
    "im a_hugger": "(⊃｡•́‿•̀｡)⊃",
    "im going for a walk": "ᕕ( ᐛ )ᕗ",
    "indeed": "ಠ_ರೃ",
    "injured": "(҂◡_◡)",
    "innocent face": "ʘ‿ʘ",
    "it's cool bro": "༼ つ ▀_▀ ༽つ",
    "jake": "ˁ(oᴥo)ˀ",
    "japanese lion face": "°‿‿°",
    "jazz musician": "ヽ(⌐■_■)ノ♪♬",
    "joint": "<\\\\\\\\> ~~~~",
    "joy": "n_n",
    "judgemental": "{ಠʖಠ}",
    "judging": "( ఠ ͟ʖ ఠ)",
    "kawaï": "∩( ・ω・)∩",
    "kilroy": "ɯ-(ꞌʊꞌ)-ɯ",
    "kirby": "⊂(◉‿◉)つ",
    "kisses": "(づ ￣ ³￣)づ",
    "kissing": "( ˘ ³˘)♥",
    "kita": "ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!",
    "kitty emote": "ᵒᴥᵒ#",
    "kitty": "=^..^=",
    "koala": "@( * o * )@",
    "kyle": "♥♥ˁ(⦿ᴥ⦿)ˀ♥♥",
    "laughing": "(＾▽＾)",
    "lenny": "( ͡° ͜ʖ ͡°)",
    "listening to headphones": "◖ᵔᴥᵔ◗ ♪ ♫",
    "lodash flip": "(╯°□°）╯︵ ɥsɐpoן",
    "looking down": "(._.)",
    "love you": "ᵛᵉᵧₒᵤᶫᵒᵛᵉᵧₒᵤ ᶫᵒᵛᵉᵧₒᵤ",
    "love": "(♥_♥)",
    "mac": "",
    "man spider": "/╲/\\༼ *ಠ 益 ಠ* ༽/\\╱\\",
    "manatee": "(◕('''' 人 '''') ◕)",
    "meditation": "‿( ́ ̵ _-`)‿",
    "mega rage": "＼＼\\٩(๑`^´๑)۶//／／",
    "meh": "¯\\(°_o)/¯",
    "meow": "ฅ^•ﻌ•^ฅ",
    "metal": "\\m/_(>_<)_\\m/",
    "middle fingers": "┌∩┐(◣ _ ◢)┌∩┐",
    "monkey": "@(_)@",
    "monocle": "(╭ರ_•́)",
    "mouse": "----{,_,\">",
    "myancat": "mmmyyyyy<⦿⽘⦿>aaaannn",
    "needle": "┣▇▇▇═─",
    "neo": "(⌐■_■)--︻╦╤─ - - -",
    "no support": "乁( ◔ ౪◔)「 ┑(￣д ￣)┍",
    "nope": "t(-_-t)",
    "oh hi!": "┬┴┬┴┤･ω･)ﾉ├┬┴┬┴",
    "oh you": "(n˘v˘•)¬",
    "omg yes": "(๑˃̵ᴗ˂̵)و",
    "opera": "ヾ(´〇`)ﾉ♪♪♪",
    "owo": "owo",
    "pac man": "ᗧ···ᗣ···ᗣ··",
    "pancakes?": "( ^-^)_旦",
    "panda": "ヽ(￣(ｴ)￣)ﾉ",
    "peace": "(‾⌣‾)♉",
    "peepers": "ಠಠ",
    "pig": "^(*(oo)*)^",
    "piggy": "(∩◕(oo)◕∩)",
    "ping pong": "( _)0*´¯`·.¸.·´¯`°q(_ )",
    "pirate flag": "?‍☠️",
    "playing in snow": "(╯^□^)╯︵ ❄☃❄",
    "point": "(☞ﾟヮﾟ)☞",
    "pointing": "(☞ﾟヮﾟ)☞",
    "polar bear": "ʕ·͡ᴥ·ʔ",
    "porcupine": "(•ᴥ• )́`́''''́`́''''́⻍",
    "pretty eyes": "ఠ_ఠ",
    "punch": "o=(-q)",
    "pup": "ᶘ ◕ᴥ◕ᶅ",
    "put table back": "┏━┓ ︵ /(^.^/)",
    "put the table back": "┬─┬ ノ( ゜-゜ノ)",
    "questionable": "(ծ‸ ծ)",
    "race car": "ō͡≡o˞̶",
    "rage face": "ლ(ಠ益ಠ)ლ",
    "rage": "ლ(ಠ益ಠ)ლ",
    "rare": "┌ಠ_ಠ)┌∩┐ ᶠᶸᶜᵏ♥ᵧₒᵤ",
    "reddit disapproval face": "ಠ_ಠ",
    "resting my eyes": "ᴖ̮ ̮ᴖ",
    "riot": "୧༼ಠ益ಠ༽୨",
    "robot": "d[o_0]b",
    "rock on": "\\m/ (>.<) \\m/",
    "rose": "-----------<----(@",
    "round bird": ",(u°)>",
    "round cat": "~(^._.)",
    "running": "ε=ε=ε=┌(;*´д`)ﾉ",
    "sad and confused": "¯\\_(⊙︿⊙)_/¯",
    "sad and crying": "(ᵟຶ︵ ᵟຶ)",
    "sad donger": "ヽ༼ຈʖ̯ຈ༽ﾉ",
    "sad face": "(ಥ⌣ಥ)",
    "sad lenny": "( ͡° ʖ̯ ͡°)",
    "sailor moon": "/¯\\_/°^_^°\\_/¯\\",
    "salesforce": "(╯°□°）╯︵ ǝɔɹoɟsǝlɐs",
    "satan": "↑_(φwφ;)ψ",
    "satisfied": "(◠﹏◠)",
    "scream ghost": ".----------.",
    "seal": "(ᵔᴥᵔ)",
    "shark attack": "~~~~~~\\o/~~~~~/\\~~~~~",
    "shark face": "( ˇ෴ˇ )",
    "shocked": "(∩╹□╹∩)",
    "shoot": "(◕_◕)=ε/̵͇̿̿/''''̿''''̿ ̿",
    "shrug face": "¯\\_(ツ)_/¯",
    "shrug": "¯\\_(ツ)_/¯",
    "shruggie": "¯\\_(ツ)_/¯",
    "shy": "(๑•́ ₃ •̀๑)",
    "singing": "♪└(￣◇￣)┐♪",
    "skrillex": "ϟƙʀɩןןσx ",
    "sleepy coffee": "( -_-)旦~",
    "sleepy": "눈_눈",
    "smiley toast": "ʕʘ̅͜ʘ̅ʔ",
    "smooth": "(づ ￣ ³￣)づ ⓢⓜⓞⓞⓣⓗ",
    "snail": "@_''''-''''",
    "sniper rifle": "︻デ┳═ー",
    "sniper": "︻デ┳═ー",
    "snowing": "✲´*。.❄¨¯`*✲。❄。*。",
    "sophie": "<xx\"\"xx>",
    "sorry": "ヾ(_ _。）",
    "sparkle": "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
    "spell cast": "╰( ⁰ ਊ ⁰ )━☆ﾟ.*･｡ﾟ",
    "spider": "/x\\(-)/x\\",
    "spooky": "‹’’›(ͼ˳ͽ)‹’’›",
    "squee": "ヾ(◎o◎,,；)ﾉ",
    "squid": "くコ:彡",
    "squinting bear": "ʕᵔᴥᵔʔ",
    "staring": "٩(๏_๏)۶",
    "stick up your dukes": "(ง’-‘)ง",
    "stranger danger": "(づ｡◕‿‿◕｡)づ",
    "strut": "ᕕ( ᐛ )ᕗ",
    "stunna shades": "(っ▀¯▀)つ",
    "sunglasses": "(•_•)>⌐■-■ (⌐■_■)",
    "surprised": "（ ﾟдﾟ）",
    "sword 2": "▬▬ι═══════>",
    "sword": "@xxxx[{::::::::::::::>",
    "table flip": "(╯°□°）╯︵ ┻━┻",
    "taking a_dump": "(⩾﹏⩽)",
    "tgif": "ヽ(´▽｀)ノ",
    "things that cant be unseen": "♨_♨",
    "this guy": "(☞ﾟ∀ﾟ)☞",
    "tidy up": "┬─┬⃰͡ (ᵔᵕᵔ͜ )",
    "tie fighter": "|-o-|",
    "tired": "( ͡ಠ ʖ̯ ͡ಠ)",
    "touchy feely": "ԅ(≖‿≖ԅ)",
    "trick": "+1 @skardude",
    "tripping out": "q(❂‿❂)p",
    "trolling": "༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽",
    "trumpet": "-=iii=<()",
    "unicorn": "?",
    "upc": "║▌║█║▌│║▌║▌█",
    "upside down lenny": "( ͜。 ͡ʖ ͜。)",
    "uwu / cute face": "(uwu)",
    "victory!": "v(-.o)v",
    "wat-wat": "σ(‘◉⌓◉’)",
    "wat": "ಠ_ಠ",
    "wave dance": "~(^-^)~",
    "what (waat)": "＼（〇_ｏ）／",
    "what????": "(ͼ˳ͽ)..!!!",
    "whistling": "(っ•́｡•́)♪♬",
    "why?!": "ლ( `д’ ლ)",
    "winnie the pooh": "ʕ •́؈•̀)",
    "winning": "(•̀ᴗ•́)و ̑̑",
    "wizard": "(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ. *",
    "worried": "(´･_･`)",
    "wtf dude?": "＼(◑д◐)＞∠(◑д◐)",
    "wtf why": "(｢๑•₃•)｢ ʷʱʸ?",
    "y u no": "ლ(ಠ_ಠლ)",
    "yessir": "∠(･`_´･ )",
    "yum": "(っ˘ڡ˘ς)",
    "zoidberg": "(\\/) (;,,;) (\\/)",
    "zombie": "[¬º-°]¬",
    "zoned": "(⊙_◎)"
}

exports.inspire = (req, res, next) => {
  var botPayload = {
    attachments: [],
    response_type: 'in_channel',
  };
  
  try {
    botPayload.text = emojis[req.body.text];
  } catch (e) {
    botPayload.text = "";
  }

  return res.status(200).json(botPayload);
}
